#!/bin/sh

export GIT_DIR=pidgin.git

git init

git_marks="marks-git"
mtn_marks="marks-mtn"

touch $git_marks $mtn_marks

# clean
# options="--use-one-changelog"

# final
options="--log-revids --log-certs"

mtn --db pidgin.mtn pull
mtn --rcfile mtn-hooks.lua git_export --db pidgin.mtn --authors-file=authors-map --branches-file=branches-map \
        --refs=revs --import-marks=$mtn_marks --export-marks=$mtn_marks $options |
        git fast-import --import-marks=$git_marks --export-marks=$git_marks
